export const GET_INGRIDIENTS__REQUEST = 'GET_INGRIDIENTS__REQUEST';
export const GET_INGRIDIENTS__SUCCESS = 'GET_INGRIDIENTS__SUCCESS';
export const GET_INGRIDIENTS__FAILURE = 'GET_INGRIDIENTS__FAILURE';