export const ADD_INGRIDIENT = 'ADD_INGRIDIENT';
export const DELETE_INGRIDIENT = 'DELETE_INGRIDIENT';
export const CLEAR_CONSTRUCTOR = 'CLEAR_CONSTRUCTOR';
export const SORT_INGRIDIENT = 'SORT_INGRIDIENT';

export const GET_INGRIDIENTS__REQUEST = 'GET_INGRIDIENTS__REQUEST';
export const GET_INGRIDIENTS__SUCCESS = 'GET_INGRIDIENTS__SUCCESS';
export const GET_INGRIDIENTS__FAILURE = 'GET_INGRIDIENTS__FAILURE';

export const GET_ORDER__REQUEST = 'GET_ORDER__REQUEST';
export const GET_ORDER__SUCCESS = 'GET_ORDER__SUCCESS';
export const GET_ORDER__FAILURE = 'GET_ORDER__FAILURE';

export const GET_PASSWORD_FORGOT__REQUEST = 'GET_PASSWORD_FORGOT__REQUEST';
export const GET_PASSWORD_FORGOT__SUCCESS = 'GET_PASSWORD_FORGOT__SUCCESS';
export const GET_PASSWORD_FORGOT__FAILURE = 'GET_PASSWORD_FORGOT__FAILURE';

export const GET_PASSWORD_RESET__REQUEST = 'GET_PASSWORD_RESET__REQUEST';
export const GET_PASSWORD_RESET__SUCCESS = 'GET_PASSWORD_RESET__SUCCESS';
export const GET_PASSWORD_RESET__FAILURE = 'GET_PASSWORD_RESET__FAILURE';

export const GET_REGISTER__REQUEST = 'GET_REGISTER__REQUEST';
export const GET_REGISTER__SUCCESS = 'GET_REGISTER__SUCCESS';
export const GET_REGISTER__FAILURE = 'GET_REGISTER__FAILURE';

export const GET_LOGIN__REQUEST = 'GET_LOGIN__REQUEST';
export const GET_LOGIN__SUCCESS = 'GET_LOGIN__SUCCESS';
export const GET_LOGIN__FAILURE = 'GET_LOGIN__FAILURE';

export const GET_UPDATE__REQUEST = 'GET_UPDATE__REQUEST';
export const GET_UPDATE__SUCCESS = 'GET_UPDATE__SUCCESS';
export const GET_UPDATE__FAILURE = 'GET_UPDATE__FAILURE';

export const GET_LOGOUT__REQUEST = 'GET_LOGOUT__REQUEST';
export const GET_LOGOUT__SUCCESS = 'GET_LOGOUT__SUCCESS';
export const GET_LOGOUT__FAILURE = 'GET_LOGOUT__FAILURE';

export const WS_CONNECTION_START: 'WS_CONNECTION_START' = 'WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';
export const WS_GET_ORDERS: 'WS_GET_ORDERS' = 'WS_GET_ORDERS';

export const WS_CONNECTION_START_USER: 'WS_CONNECTION_START_USER' = 'WS_CONNECTION_START_USER';
export const WS_CONNECTION_SUCCESS_USER: 'WS_CONNECTION_SUCCESS_USER' = 'WS_CONNECTION_SUCCESS_USER';
export const WS_CONNECTION_ERROR_USER: 'WS_CONNECTION_ERROR_USER' = 'WS_CONNECTION_ERROR_USER';
export const WS_CONNECTION_CLOSED_USER: 'WS_CONNECTION_CLOSED_USER' = 'WS_CONNECTION_CLOSED_USER';
export const WS_GET_ORDERS_USER: 'WS_GET_ORDERS_USER' = 'WS_GET_ORDERS_USER';